serverAddr = "127.0.0.1"
serverPort = {{ .Envs.FRP_SERVER_PORT }}

[[visitors]]
name = "minecraft-server-visitor"
type = "stcp"
serverName = "minecraft-server"
secretKey = "{{ .Envs.MC_FRP_SECRET_KEY }}"
bindAddr = "0.0.0.0"
bindPort = {{ .Envs.MC_SERVER_FRP_PORT }}
